### PR TITLE
Proxy Overhaul 

### PR DESCRIPTION
**Pull request by jmchilton**
- IT work from @hexylena 
- Double proxy from @natefoo 
- Test cases for both of these.
- Improved package structure - aiming for a release to npm.
- Use a main function instead of a script, for more robust testing.
- Use prettier on the codebase. 

Should we just keep this codebase as is for GIEs and create a galaxyproject/gxit-nodejs-proxy repo for the IT version of this project?

Is everyone on board for publishing this properly as a package instead of remerging it into the Galaxy codebase?

It would only be a couple hours to update this to support GIEs and GxITs but @natefoo and I decided that was maybe not worth the effort.

### CODE REVIEW

**Comment by hexylena** [comment]
> Should we just keep this codebase as is for GIEs and create a galaxyproject/gxit-nodejs-proxy repo for the IT version of this project?

I don't know. if you don't feel it's worth it to support both, that's fine for me. Can't say I disagree. It feels like the introduction of gxit is already bungled since now we have two solutions for the same thing and no planned unification, so what's one duplicated proxy in addition?

I'm happy for both of these to be merged to galaxyproject, no reason to have this under usegalaxy-eu, or worse one under each.

> Is everyone on board for publishing this properly as a package instead of remerging it into the Galaxy codebase?

totes!

**Comment by jmchilton** [comment]
I've published it here:

https://www.npmjs.com/package/gx-it-proxy

If we do decide to unify I did reserve galaxy-proxy also before deciding to change the name:

https://www.npmjs.com/package/galaxy-proxy

I can't figure out how to make npm just take a bin entry and create a standalone environment unfortunately - so I'm not actually sure of a good way to use the published package. Adding it to Galaxy's client package.json and putting a little entrypoint in there seems to work fine but it isn't a client concern so I suppose it doesn't belong there:

```
~/w/g/client % yarn it-proxy --version
yarn run v1.3.2
$ gx-it-proxy --version
0.0.3
✨  Done in 0.32s.
~/w/g/client % yarn it-proxy --port 8012 --verbose
yarn run v1.3.2
$ gx-it-proxy --port 8012 --verbose
Listening on localhost:8012
```

Do we want to move this repo or should we keep this one and just create a README entry pointing at say galaxyproject/gx-it-proxy? I'm fine either way.

**Comment by hexylena** [comment]
awesome @ reserving both!

I'd vote move? just keep all of it under galaxyproject. guess it's less breakage prone if anyone is actually using this

**Comment by jmchilton** [comment]
I don't have access to move it - does anyone?

**Comment by hexylena** [comment]
I think the intersection of eu repo admins, galaxy repo admins is a null set, so, going to fix that for this repo: https://github.com/usegalaxy-eu/gie-nodejs-proxy/invitations thanks!

**Comment by bgruening** [comment]
@jmchilton please let me know if you can still not transfer it.

**Comment by jmchilton** [comment]
Transferred and renamed to gx-it-proxy. Thanks so much! I've given the docker-devops group pretty broad access to the repo - if additional permissions are desired don't hesitate to ask.

**Comment by hexylena** [comment]
Sounds good! Thanks for doing this.

**Pull request merged**
